export const APP_LOAD = "APP_LOAD";
export const REDIRECT = "REDIRECT";
export const SET_PAGE = "SET_PAGE";
export const APPLY_TAG_FILTER = "APPLY_TAG_FILTER";
export const CHANGE_TAB = "CHANGE_TAB";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const LOGIN_PAGE_UNLOADED = "LOGIN_PAGE_UNLOADED";
export const REGISTER_PAGE_UNLOADED = "REGISTER_PAGE_UNLOADED";
export const UPDATE_FIELD_AUTH = "UPDATE_FIELD_AUTH";
export const ASYNC_START = "ASYNC_START";
export const ASYNC_END = "ASYNC_END";
export const ASYNC_SUCCESS = "ASYNC_SUCCESS";
export const ASYNC_FAIL = "ASYNC_FAIL";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const Modal = {
  SHOW_MODAL: "SHOW_MODAL",
  HIDE_MODAL: "HIDE_MODAL",
  CHANGE_MODAL_CONTENT: "CHANGE_MODAL_CONTENT",
  CHANGE_MODAL_TITLE: "CHANGE_MODAL_TITLE",
};

export const DyePlant = {
  FETCH_LIST_DYEPLANT: "FETCH_LIST_DYEPLANT",
  FETCH_LIST_DYEPLANT_SUCCESS: "FETCH_LIST_DYEPLANT_SUCCESS",
  FETCH_LIST_DYEPLANT_FAILED: "FETCH_LIST_DYEPLANT_FAILED",
  FETCH_DETAIL_DYEPLANT: "FETCH_DETAIL_DYEPLANT",
  FETCH_DETAIL_DYEPLANT_SUCCESS: "FETCH_DETAIL_DYEPLANT_SUCCESS",
  FETCH_DETAIL_DYEPLANT_FAILED: "FETCH_DETAIL_DYEPLANT_FAILED",
  UPDATE_DETAIL_DYEPLANT: "EDIT_DETAIL_DYEPLANT",
  UPDATE_DETAIL_DYEPLANT_SUCCESS: "EDIT_DETAIL_DYEPLANT_SUCCESS",
  UPDATE_DETAIL_DYEPLANT_FAILED: "EDIT_DETAIL_DYEPLANT_FAILED",
};

export const Order = {
  FETCH_LIST_ORDER: "FETCH_LIST_ORDER",
  FETCH_LIST_ORDER_SUCCESS: "FETCH_LIST_ORDER_SUCCESS",
  FETCH_LIST_ORDER_FAILED: "FETCH_LIST_ORDER_FAILED",
  FETCH_DETAIL_ORDER: "FETCH_DETAIL_ORDER",
  FETCH_DETAIL_ORDER_SUCCESS: "FETCH_DETAIL_ORDER_SUCCESS",
  FETCH_DETAIL_ORDER_FAILED: "FETCH_DETAIL_ORDER_FAILED",
};

export const Import = {
  FETCH_LIST_IMPORT: "FETCH_LIST_IMPORT",
  FETCH_LIST_IMPORT_SUCCESS: "FETCH_LIST_IMPORT_SUCCESS",
  FETCH_LIST_IMPORT_FAILED: "FETCH_LIST_IMPORT_FAILED",
  FETCH_DETAIL_IMPORT: "FETCH_DETAIL_IMPORT",
  FETCH_DETAIL_IMPORT_SUCCESS: "FETCH_DETAIL_IMPORT_SUCCESS",
  FETCH_DETAIL_IMPORT_FAILED: "FETCH_DETAIL_IMPORT_FAILED",
};

export const DyeBatch = {
  FETCH_LIST_DYEBATCH: "FETCH_LIST_DYEBATCH",
  FETCH_LIST_DYEBATCH_SUCCESS: "FETCH_LIST_DYEBATCH_SUCCESS",
  FETCH_LIST_DYEBATCH_FAILED: "FETCH_LIST_DYEBATCH_FAILED",
};

export const Raw = {
  FETCH_LIST_RAW_STOCK: "FETCH_LIST_RAW_STOCK",
  FETCH_LIST_RAW_STOCK_SUCCESS: "FETCH_LIST_RAW_STOCK_SUCCESS",
  FETCH_LIST_RAW_STOCK_FAILED: "FETCH_LIST_RAW_STOCK_FAILED",
  FETCH_LIST_RAW_ALL_PLANT: "FETCH_LIST_RAW_ALL_PLANT",
  FETCH_LIST_RAW_ALL_PLANT_SUCCESS: "FETCH_LIST_RAW_ALL_PLANT_SUCCESS",
  FETCH_LIST_RAW_ALL_PLANT_FAILED: "FETCH_LIST_RAW_ALL_PLANT_FAILED",
  FETCH_LIST_FABRIC_DYEPLANT: "FETCH_LIST_FABRIC_DYEPLANT",
  FETCH_LIST_FABRIC_DYEPLANT_SUCCESS: "FETCH_LIST_FABRIC_DYEPLANT_SUCCESS",
  FETCH_LIST_FABRIC_DYEPLANT_FAILED: "FETCH_LIST_FABRIC_DYEPLANT_FAILED",
};


