export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const Alert = {
  SHOW_SUCCESS_MESSAGE: "SHOW_SUCCESS_MESSAGE",
  HIDE_SUCCESS_MESSAGE: "HIDE_SUCCESS_MESSAGE",
  SHOW_ERROR_MESSAGE: "SHOW_ERROR_MESSAGE",
  HIDE_ERROR_MESSAGE: "HIDE_ERROR_MESSAGE",
};

export const Auth = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  REGISTER: "REGISTER",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILED: "REGISTER_FAILED",
  LOGOUT: "LOGOUT",
};

export const Modal = {
  SHOW_MODAL: "SHOW_MODAL",
  HIDE_MODAL: "HIDE_MODAL",
  CHANGE_MODAL_CONTENT: "CHANGE_MODAL_CONTENT",
  CHANGE_MODAL_TITLE: "CHANGE_MODAL_TITLE",
};

export const DyePlant = {
  FETCH_LIST_DYEPLANT: "FETCH_LIST_DYEPLANT",
  FETCH_LIST_DYEPLANT_SUCCESS: "FETCH_LIST_DYEPLANT_SUCCESS",
  FETCH_LIST_DYEPLANT_FAILED: "FETCH_LIST_DYEPLANT_FAILED",
  FETCH_DETAIL_DYEPLANT: "FETCH_DETAIL_DYEPLANT",
  FETCH_DETAIL_DYEPLANT_SUCCESS: "FETCH_DETAIL_DYEPLANT_SUCCESS",
  FETCH_DETAIL_DYEPLANT_FAILED: "FETCH_DETAIL_DYEPLANT_FAILED",
  UPDATE_DETAIL_DYEPLANT: "EDIT_DETAIL_DYEPLANT",
  UPDATE_DETAIL_DYEPLANT_SUCCESS: "EDIT_DETAIL_DYEPLANT_SUCCESS",
  UPDATE_DETAIL_DYEPLANT_FAILED: "EDIT_DETAIL_DYEPLANT_FAILED",
};

export const Order = {
  FETCH_LIST_ORDER: "FETCH_LIST_ORDER",
  FETCH_LIST_ORDER_SUCCESS: "FETCH_LIST_ORDER_SUCCESS",
  FETCH_LIST_ORDER_FAILED: "FETCH_LIST_ORDER_FAILED",
  FETCH_DETAIL_ORDER: "FETCH_DETAIL_ORDER",
  FETCH_DETAIL_ORDER_SUCCESS: "FETCH_DETAIL_ORDER_SUCCESS",
  FETCH_DETAIL_ORDER_FAILED: "FETCH_DETAIL_ORDER_FAILED",
  CREATE_ORDER: "CREATE_ORDER",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAILED: "CREATE_ORDER_FAILED",
};

export const Import = {
  FETCH_LIST_IMPORT: "FETCH_LIST_IMPORT",
  FETCH_LIST_IMPORT_SUCCESS: "FETCH_LIST_IMPORT_SUCCESS",
  FETCH_LIST_IMPORT_FAILED: "FETCH_LIST_IMPORT_FAILED",
  FETCH_DETAIL_IMPORT: "FETCH_DETAIL_IMPORT",
  FETCH_DETAIL_IMPORT_SUCCESS: "FETCH_DETAIL_IMPORT_SUCCESS",
  FETCH_DETAIL_IMPORT_FAILED: "FETCH_DETAIL_IMPORT_FAILED",
};

export const DyeBatch = {
  FETCH_LIST_DYEBATCH: "FETCH_LIST_DYEBATCH",
  FETCH_LIST_DYEBATCH_SUCCESS: "FETCH_LIST_DYEBATCH_SUCCESS",
  FETCH_LIST_DYEBATCH_FAILED: "FETCH_LIST_DYEBATCH_FAILED",
};

export const Raw = {
  // List raw in stock
  FETCH_LIST_RAW_STOCK: "FETCH_LIST_RAW_STOCK",
  FETCH_LIST_RAW_STOCK_SUCCESS: "FETCH_LIST_RAW_STOCK_SUCCESS",
  FETCH_LIST_RAW_STOCK_FAILED: "FETCH_LIST_RAW_STOCK_FAILED",

  // List fabric one plant
  FETCH_LIST_FABRIC_DYEPLANT: "FETCH_LIST_FABRIC_DYEPLANT",
  FETCH_LIST_FABRIC_DYEPLANT_SUCCESS: "FETCH_LIST_FABRIC_DYEPLANT_SUCCESS",
  FETCH_LIST_FABRIC_DYEPLANT_FAILED: "FETCH_LIST_FABRIC_DYEPLANT_FAILED",

  // List raw all plant
  FETCH_LIST_RAW_ALL_PLANT: "FETCH_LIST_RAW_ALL_PLANT",
  FETCH_LIST_RAW_ALL_PLANT_SUCCESS: "FETCH_LIST_RAW_ALL_PLANT_SUCCESS",
  FETCH_LIST_RAW_ALL_PLANT_FAILED: "FETCH_LIST_RAW_ALL_PLANT_FAILED",

  // List fabric type
  FETCH_LIST_FABRIC_TYPE: "FETCH_LIST_FABRIC_TYPE",
  FETCH_LIST_FABRIC_TYPE_SUCCESS: "FETCH_LIST_FABRIC_TYPE_SUCCESS",
  FETCH_LIST_FABRIC_TYPE_FAILED: "FETCH_LIST_FABRIC_TYPE_FAILED",
};

export const Export = {
  // List raw prepare to export
  FETCH_LIST_RAW_EXPORT: "FETCH_LIST_RAW_EXPORT",
  FETCH_LIST_RAW_EXPORT_SUCCESS: "FETCH_LIST_RAW_EXPORT_SUCCESS",
  FETCH_LIST_RAW_EXPORT_FAILED: "FETCH_LIST_RAW_EXPORT_FAILED",

  // Create export
  CREATE_EXPORT: "CREATE_EXPORT",
  CREATE_EXPORT_SUCCESS: "CREATE_EXPORT_SUCCESS",
  CREATE_EXPORT_FAILED: "CREATE_EXPORT_FAILED",
};
