export const LOG_IN_FORM = "LOG_IN_FORM";
export const DYE_PLANT_FORM = "DYE_PLANT_FORM";
export const CREATE_EXPORT_FORM = "CREATE_EXPORT_FORM";
export const CREATE_ORDER_FORM = "CREATE_ORDER_FORM";
export const INFO_FORM = "INFO_FORM";
export const LIST_FABRIC_FORM = "LIST_FABRIC_FORM";
export const RECALL_FORM = "RECALL_FORM";
export const PAYMENT_FORM = "PAYMENT_FORM";